version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y python3-pip
            pip3 install pyinstaller
            pip3 install -r requirements.txt

      - run:
          name: Build .exe
          command: |
            pyinstaller --noconfirm --onefile --windowed --icon="./dnsed/assets/app.ico" --name="DNSed" --add-data="./dnsed/assets:assets/"  "./dnsed/main.py"
            ls
            ls -la dist

      - store_artifacts:
          path: dist/



workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - dev
